name: 🐞 Bug
description: File a bug in 白い熊 暗記
labels:  ["Needs Triage"]

body:

  - type: checkboxes
    id: contact
    attributes:
      label: Checked for duplicates?
      description: Quickly search the existing issues to see if a similar issue exists
      options:
        - label: This issue is not a duplicate
          required: true

  - type: textarea
    id: steps
    attributes:
      label: What are the steps to reproduce this bug?
      description: Briefly explain what you did which caused this bug to occur
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: Briefly describe what happened, and what should have happened
    validations:
      required: true

  - type: textarea
    id: debug-info
    attributes:
      label: Debug info
      description: Settings - About (bottom of the list) - Copy debug info
      placeholder: Debug Info (Starts with the app version)
      render: text
    validations:
      required: true

  - type: textarea
    id: extra_info
    attributes:
      label: (Optional) Anything else you want to share?
      placeholder: List any extra information

  - type: checkboxes
    id: research
    attributes:
      label: Research
      description: Confirm the points below
      options:
        - label: I have searched and could not find a solution to my issue
          required: true
        - label: (Optional) I have confirmed the issue is not resolved in the latest release
          required: false
